USSF-ORBIT/ussf-portal

docs/adr/0010-playwright-e2e-cms.md
Adds an ADR documenting the choice to use Playwright to E2E test the CMS.
Corresponding PR that makes this change in the CMS is here: https://github.com/USSF-ORBIT/ussf-portal-cms/pull/29
=> Playwright ADR

.github/workflows/reusable-run-e2e-tests.yml, .github/workflows/skip-e2e-tests.yml, docs/how-to/run-or-update-e2e-tests.md
Add documentation on how to run and update the E2E tests now that they have moved to their own repostiroy.
Read and try `docs/how-to/run-or-update-e2e-tests.md`
See `docs/how-to/run-or-update-e2e-tests.md`
=> docs: add how to run e2e tests

docs/README.md, docs/adr/0012-playwrigt-e2e-client.md
New ADR proposing switching to playwright for e2e tests over cypress.
=> docs: add adr about switching to playwright for e2e tests

.github/workflows/reusable-run-e2e-tests.yml, .github/workflows/run-e2e-tests.yml, e2e/docker-compose.yml
- login to ECR and pass CMS and Portal Client repository IDs to docker-compose.yml
- docker-compose.yml will use the cache when available, otherwise will build without it
---
You can test that the docker-compose.yml file still works locally. I recommend cloning the [e2e repo](https://github.com/USSF-ORBIT/ussf-portal) and running `yarn services:up` from inside the /e2e folder. This will test the Dockerfile changes with `docker compose`.
---
=> ci: improve docker build times using ecr cache

e2e/docker-compose.yml
- extend the connection timeout from CMS App to Keystone DB from the default 5 seconds to 10 seconds
- add a health check to Keystone DB so CMS App waits until it is healthy in Docker Compose
This change only modifies how Docker Compose operates locally. In AWS, the connection string will have to be modified in AWS Systems Manager Parameter Store.
=> dev: extend connection timeout and add keystone db health check

.github/workflows/reusable-run-e2e-tests.yml
move gh-docker-logs later in the e2e workflow
=> ci: capture docker logs later

.github/workflows/reusable-run-e2e-tests.yml
- always capture docker logs in e2e workflow, even when playwright or cypress fail
=> ci: always capture docker logs

.github/workflows/reusable-run-e2e-tests.yml, e2e/package.json, e2e/yarn.lock
I was seeing failures in the e2e tests that seemed to be failing because the server wasn't ready. Locally after ensuring the servers were up the tests did not fail, so this pr adds `wait-on` an npm package that waits for a url to return 200 ok. It has other features but seemed better than a bash while loop. See https://github.com/jeffbski/wait-on
2 new steps added to wait for the cms and client.
=> test: update e2e workflow to wait for the client and cms servers to be ready

.github/workflows/reusable-run-e2e-tests.yml, e2e/docker-compose.yml, e2e/package.json
As part of adding ` LAUNCHDARKLY_SDK_CLIENT_SIDE_ID` to the checked vars the portal client doesn't start up. This PR adds a value for it so that the server will start up. It uses the recently added local configuration option defined in USSF-ORBIT/ussf-portal-client#839. 839 isn't required for this PR to pass the build, but that PR requires the changes in this PR.
Make sure the build passes, try it locally if you want.
=> build: support local file to set launch darkly flags

e2e/docker-compose.yml, e2e/package.json
This update allows local e2e builds to work on all platforms, since distroless does not build on M1 Macbooks without requiring changes to the Dockerfile.
Test this out locally with `yarn services:up` and `yarn e2e:test` as you normally would do to run local e2e tests.
=> chore: make local e2e builds work on all platforms

e2e/cypress/e2e/sites-and-applications.cy.js
Disable some flakey tests 😞 
Some of the tests in the `sites-and-applications.cy.js` are extra flakey. I spent time trying to diagnose it but have come to an impasse. So after discussing this internally we've decided to turn off these tests for now pending when we can convert them to playwright. Conversion to playwright is blocked by sc-1375.
`yarn services:up`
`yarn cypress:test`
=> test: skip tests that are extra flakey but slated for playwright conversion

.github/settings.yml, .github/workflows/run-e2e-tests.yml, .github/workflows/skip-e2e-tests.yml
- change the job title of `run-e2e-tests` in `.github/workflows/run-e2e-tests.yml` and `.github/workflows/skip-e2e-tests.yml` to `check-e2e-tests` to differentiate from the reusable job
- also makes it more clear that the job is a check for whether e2e tests will run, and that the e2e tests can be skipped in some runs
=> chore: changed run-e2e-tests job to check-e2e-tests

e2e/playwright/feature/article-hero-carousel.spec.ts
Add new e2e test for showing the hero image in the carousel for Internal News articles
This is largely copied from the article hero spec. It's in a separate file to facilitate parallel tests and also tests seeing a hero image for the Internal News articles, even though the underling code for it is shared with Orbit blog articles.
Run the e2e tests if you like:
```sh
yarn services:up -d
yarn wait-on http://localhost:3000/api/sysinfo http://localhost:3001/api/sysinfo && yarn e2e:test
```
=> test: add test for carousel showing hero image

e2e/playwright/cms/tests/article.spec.ts, e2e/playwright/cms/tests/tracking.spec.ts, e2e/playwright/feature/article-hero-carousel.spec.ts, e2e/playwright/feature/article-hero.spec.ts, e2e/playwright/models/KeystoneList.ts
Adds an e2e helper `gotoAndSortBy` that will go to a CMS page after adding the `sortBy` query parameters to sort the data as needed by the test to locate its data.
We only hit an issue once the page with the list has more than 50 items causing it to appear on page two.
NOTE: this PR is based on #187 so it includes that test too
Run the tests
```sh
yarn services:up -d
yarn wait-on http://localhost:3000/api/sysinfo http://localhost:3001/api/sysinfo && yarn e2e:test
```
If you want to create a bunch of data mare one of the tests that creates an article or event with `.only` and then run, assuming `yarn services:up -d` is still running
```sh
for i in {1..50}; do yarn e2e:test; done
```
=> test: e2e improvements

e2e/playwright/feature/article-preview.spec.ts, e2e/playwright/feature/article-scheduler.spec.ts
Fixed scheduler tests that break due to preview and added specific tests.
No, depends on https://github.com/USSF-ORBIT/ussf-portal-client/pull/934 and https://github.com/USSF-ORBIT/ussf-portal-cms/pull/267
```sh
yarn services:removeall 
yarn services:up -d
yarn wait-on http://localhost:3000/api/sysinfo http://localhost:3001/api/sysinfo
yarn e2e:test
```
=> test: Add tests for article preview

e2e/playwright/feature/article-embed-video.spec.ts, e2e/playwright/models/KeystoneArticle.ts
Add test for embedding a YouTube video in an article
If you want to run this locally, be sure to have both the portal and cms on the `jc-investigate-video` branch
CMS PR: https://github.com/USSF-ORBIT/ussf-portal-cms/pull/260/
Portal client PR: https://github.com/USSF-ORBIT/ussf-portal-client/pull/923/
To run locally:
- `yarn services:up -d`
- `yarn e2e:test`
=> test: Add test for embedding video in an article

.github/workflows/reusable-run-e2e-tests.yml, e2e/package.json, e2e/playwright.config.ts
Update playwright configuration to run tests against multiple browsers: Chrome, MS Edge, Firefox, and Chromium during the GitHub action that runs the e2e tests. Local development commands have been updated to only run tests against chromium.
New commands
* `yarn e2e:all` - runs all tests in all browsers. You must have Chrome and MS Edge installed separately. See [playwright browser docs](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) **NOTE** this command enforces no `.only` flagged tests.
* `yarn e2e:test` - runs all tests against only chromium, should be no difference than before.
* `yarn e2e:chrome` - runs all the tests in chrome
* `yarn e2e:firefox` - runs all the tests in firefox
* `yarn e2e:msedge` - runs all the tests in ms edge
Same as usual. Feel free to try …
=> test: Support running playwright with multiple browsers

e2e/playwright.config.ts
Firefox tests seem to take a little longer than other tests bumping the timeouts to have less flakes
Increase timeouts for firefox tests
I only increased the FF tests timeout to avoid just a blanket change. Also any real failures will take longer to realize they have failed.
```sh
yarn services:removeall
yarn services:up -d
yarn wait-on http://localhost:3000/api/sysinfo http://localhost:3001/api/sysinfo && yarn e2e:firefox
```
=> test: update firefox timeouts

renovate.json
- improve labeling so we know which package rule is executed when a dependency PR is made
- improve Node package rule so hopefully all Node updates are packaged together
- Improve lockfile maintenance on package rules that include Node dependencies
- add `digest` updateType to `github-actions` package rules so hopefully all `github-actions` updates are grouped together
=> ci: improve dependency grouping and labeling

renovate.json
- attempts to fix renovate/node branch which does not include engine updates, which when featured in renovate/dependencies branch breaks that branch.
- makes lockfile maintenance true in global config
=> fix: fixes renovate/node leaving out engine updates

.github/workflows/reusable-run-e2e-tests.yml
- Adds a conditional check so that the branch switching action is not run if the event that triggered the workflow was from a renovate branch
- Removes `ref: main` from the checkout action so that the default behavior takes over. Described here ([link](https://github.com/actions/checkout)):
```
ref: ''
```
- Removes step for checking out branches with Merge Group condition. This was added when Merge Group was being tested but as it is not viable at the moment, should be removed.
To see an example of how the E2E workflow will behave, see these two runs:
[On a branch with name starting with "renovate"](https://github.com/USSF-ORBIT/ussf-portal-cms/actions/runs/4631695603/jobs/8194878071)
[On a branch without a name starting with "renovate"](https://github.com/USSF-ORBIT/ussf-portal-cms/actio …
=> ci: prevent e2e workflow from checking out renovate branches in other repos

.github/workflows/reusable-run-e2e-tests.yml, e2e/docker-compose.yml
- Change the docker repository `cache-from` source to a new ECR repository named `docker-build-cache` which will be a dedicated repository for CMS and Client image build caches
- This will improve our build process during E2E tests because there is a higher chance that we have a cache hit because the ECR repo will be less likely to recycle our image caches
- This will improve our ECR's reliability and costs because we can use better written ECR Lifecycle Policies when the image tags are more predictable and there is a different repo for different functions.
There is a successful workflow dispatch of the E2E tests with the new ECR `cache-from` source here: https://github.com/USSF-ORBIT/ussf-portal/actions/runs/4767039781/jobs/8474809737
=> ci: use new portal-client docker-build-cache ECR

.github/workflows/reusable-run-e2e-tests.yml, e2e/docker-compose.yml
- adds a job before e2e tests to build portal-client and keystone-cms docker images and save the built images as artifacts. This can be seen in this [completed build job](https://github.com/USSF-ORBIT/ussf-portal/actions/runs/4875463241/jobs/8698258867?pr=269).
- downloads image artifacts in e2e job and loads them into docker,  so `docker compose` can use those images
These changes will save us AWS costs as the workflow will only need to pull from AWS ECR a single time rather than four times. There will be future iterative improvements but this is a good step.
=> ci: build docker images once and share artifact with parallel jobs

.github/settings.yml
Some times our changes don't trigger the build, for example changing documentation or github repo settings. This results in PRs being stuck due to the restrictions. There hasn't been a good way to allow these to be bypassed under certain conditions so we decided to allow admins to be able to bypass the restriction. This should be used sparingly.
=> chore: allow admins to bypass restrictions

e2e/playwright/portal-client/tests/sites-and-apps.spec.ts
* Updates e2e tests to match new elements for toggling sites & apps views
* Corresponds to PR https://github.com/USSF-ORBIT/ussf-portal-client/pull/1028
=> feat: Update sites and apps test to correspond with new toggle ui

.github/workflows/reusable-run-e2e-tests.yml, e2e/docker-compose.yml
- Update E2E workflow to pull Docker build cache artifacts from `build-docker-cache-artifacts.yml` in `USSF-ORBIT/ussf-portal-cms` and `USSF-ORBIT/ussf-portal-client`, and save them to Github Actions cache if not already found
- Update E2E workflow to restore `local` Docker build cache directories from Github Actions cache
- Update `docker-compose.yml` to use the `local` Docker cache directories
- Remove references to AWS ECR
=> build: use GHA cache for docker build caching

e2e/playwright/feature/announcement-scheduler.spec.ts, e2e/playwright/feature/announcement.spec.ts, e2e/playwright/feature/article-scheduler.spec.ts, e2e/playwright/feature/error-handling-404.spec.ts
And SC-2010
This PR adds a test for the 404 pages for non existent articles and a test for Call-To-Action that points to an article that was since deleted. These used to 500 but now correctly 404.
Run the tests if you want
```sh
yarn services:removeall && yarn services:up -d && yarn wait-on http://localhost:3000/api/sysinfo http://localhost:3001/api/sysinfo && yarn e2e:test
```
=> add test for fixed 404 bugs

e2e/playwright/feature/featured-shortcuts.spec.ts, e2e/playwright/feature/guardian-ideal.spec.ts, e2e/playwright/portal-client/tests/myspace.spec.ts
The PR https://github.com/USSF-ORBIT/ussf-portal-client/pull/1055 has updated link names to fix a11y issues and better support screen reader navigation. This PR updates the e2e tests for the new names.
I did notice a discrepancy of using Guardian Ideal and Guardian Ideals in different locations in the code. Not sure if that's something we should fix in this pr or leave for a later time.
```sh
yarn services:removeall && yarn services:up -d && yarn wait-on http://localhost:3000/api/sysinfo http://localhost:3001/api/sysinfo && yarn e2e:test
```
=> fix: a11y: adjusts link names to improve usability on assistive tech

e2e/playwright/feature/drag-and-drop-collections.spec.ts
Add test for dragging and dropping collections: https://github.com/USSF-ORBIT/ussf-portal-client/pull/1056
=> test: Add drag-and-drop test for collections

e2e/playwright/models/KeystoneAnnouncement.ts, e2e/playwright/models/KeystoneArticle.ts
Adds another layer of specificity to finding and selecting publish date from calendar. 
Today's date, August 22nd, 2023, revealed a fun edge case where Playwright was matching and selecting August 2 instead. This caused an error since you can't schedule an article in the past.
This is due to how Keystone renders the datepicker in HTML:
=> fix: Add weekday name to button text match

e2e/playwright/feature/search-filter.spec.ts
required for https://github.com/USSF-ORBIT/ussf-portal-client/pull/1081 to merge
adjusts search filter test to have more specificity to target with fieldset so it doesn't hit the Sites  & Applications in the footer
paired with Abigail to figure out what needed to change in the test, the test on my branch was failing because the test was grabbing the footer instead of the search filter.
=> chore: update test to make search filter test more specific to the seach filter fieldset

docs/adr/0026-use-wiremock-to-mock-third-party-apis-for-e2e-tests.md, e2e/docker-compose.yml
This PR adds an ADR explaining why we need to mock the weather api for our E2E tests. It also sets the mock endpoint.
See the other PR in the client: https://github.com/USSF-ORBIT/ussf-portal-client/pull/1108
Tests should pass as normal!
=> build: mock weather api for e2e tests

.github/workflows/reusable-run-e2e-tests.yml, e2e/playwright/feature/announcement-scheduler.spec.ts, e2e/playwright/feature/article-scheduler.spec.ts
It appears that we are coming close to the limit of free space allocated on the default Github Actions Runners. Because of our multi-stage builds, multiple repos checked out, and dependencies that have to install on the runner we need to create more disk space on the Runner. This PR should save us a considerable amount if space with a small amount of time.
- Prune unused docker images that came built-into the GHA runner
- Prune docker build cache after `docker compose` as we don't need it after the build
- Update locator to only look at button in E2E tests
=> chore: save disk space pruning unused  docker images

.github/workflows/reusable-release-please.yml
- Adds a personal access token from the spacecadets-infra@truss.works Github Account so that Release Please can trigger status checks and deploy workflow. Ref: https://github.com/google-github-actions/release-please-action#github-credentials
=> ci: add a personal access token to release please

.github/workflows/reusable-docker-cache-keystone-cms.yml, .github/workflows/reusable-docker-cache-personnel-api.yml, .github/workflows/reusable-docker-cache-portal-client.yml, e2e/docker-compose.yml
- Restores `e2e` and `builder` tags to the Docker `cache-to` and `cache-from` commands. Some PRs are getting this error `"local cache importer requires either explicit digest, \"latest\" tag or custom tag on index.json"` which seems to imply that an explicit tag is needed even though the default `latest` should do. https://github.com/moby/buildkit/blob/1efcd30d9dd67fc20bd1ec641ea6659f6e74f0d8/client/solve.go#L499C28-L499C126
=> ci: restore docker cache tags

e2e/playwright/feature/landing-page.spec.ts
Adds an e2e test to cover the functionality of the following PRs:
- https://github.com/USSF-ORBIT/ussf-portal-cms/pull/395
- https://github.com/USSF-ORBIT/ussf-portal-client/pull/1143
- https://github.com/USSF-ORBIT/ussf-portal-client/pull/1140
=> test: Add e2e test for landing pages

e2e/playwright/feature/article-preview.spec.ts, e2e/playwright/feature/landing-page.spec.ts, e2e/playwright/feature/landing-preview.spec.ts
Add tests for the new preview landing page feature. See https://github.com/USSF-ORBIT/ussf-portal-client/pull/1175 and https://github.com/USSF-ORBIT/ussf-portal-cms/pull/411.
=> feat: Support published status for landing pages and preview of draft pages

.mergify.yml
Make Mergify recognize a new label "no-merge" which must not be present for it to merge. This allows devs to easily override/prevent Mergify from acting when needed.
As far as I know, this has to be merged to be tested since it's mergify. The configuration has already been checked and is valid in Mergify.
=> Add label "no-merge" that can be used to stop automatic merging

e2e/playwright/feature/landing-page.spec.ts
Add a test to ensure landing pages show up in search
Related PRs:
- https://github.com/USSF-ORBIT/ussf-portal-cms/pull/418
- https://github.com/USSF-ORBIT/ussf-portal-client/pull/1190
=> feat: add test for searching for landing pages

e2e/playwright.config.ts, e2e/playwright/feature/settings.spec.ts
Add an e2e test for https://github.com/USSF-ORBIT/ussf-portal-client/pull/1196 to ensure that the new `userId` copy button works and the user id is displayed.
=> feat: Show user their portal userId on the settings page

e2e/playwright/feature/landing-page.spec.ts
- Add test to verify that an article with the `LandingPage` category appears in the search results with the proper permalink
Related PR: https://github.com/USSF-ORBIT/ussf-portal-cms/pull/422
=> test: Add LandingPage articles to search results

e2e/playwright/feature/guardian-directory.spec.ts
Adds a unit test for https://github.com/USSF-ORBIT/ussf-portal-client/pull/1199
I think I discovered a bug that I added to shortcut: https://app.shortcut.com/orbit-truss/story/3126/guardian-directory-search-with-empty-string-returns-incomplete-list
=> fix: show no results if none found

e2e/docker-compose.yml
For the Gravity work we created a `Dockerfile-gh` in the ussf-portal-client repo. E2E tests are not ready for gravity so this PR updates the build to use the github specific one.
=> build Use github dockerfile for client

.github/workflows/reusable-run-e2e-tests.yml
This PR pulled out a change from PR #356 to update the gha workflow. We need to update the workflow separately so the corresponding branch on `ussf-portal-client` will be able to run e2e tests properly.
=> chore: add dod cert bundle to e2e tests workflow for gha

.gitignore, docs/README.md, docs/development.md, docs/how-to/generate-jwt-test-service.md, docs/how-to/generate-jwt-token.md, e2e/.envrc, e2e/playwright/feature/jwt-auth.spec.ts
* Unskips e2e test for work on jwt test service.
* Allows .envrc to be checked in so we can have an .envrc.local that properly overrides and loads the dev cert
* Updates docs in `development.md`
* Adds new `How To` for using the service locally
=> chore: Un-skip e2e test now that code is merged in

e2e/playwright/feature/jwt-auth.spec.ts
* Adds e2e test coverage for different scenarios involving JWTs and the third-party API
You'll need the companion branch from ussf-portal-client: https://github.com/USSF-ORBIT/ussf-portal-client/pull/1209
=> chore: add e2e test for jwt

README.md, docs/development.md
This is a wild attempt on my part to refresh the README with more relevant links to project documentation. Definitely a group effort, so please feel free to pull down the branch, make changes, add your relevant sections (cc design, infra), etc. Or let me know if it's terrible and you want me to put it back! TEAMWORK.
Also added a placeholder for links to excalidraw diagrams which are in a PR here: https://github.com/USSF-ORBIT/spacecadets-dev/pull/169
=> chore: update readme with relevant links, add placeholder for excalidraw links
