USSF-ORBIT/ussf-portal

- docs/adr/0000-template.md
- docs/adr/0001-initial-portal-implementation.md
This PR adds our first ADR, as well as the standard Truss [ADR template](https://adr.github.io/madr/#the-template). The ADR describes our chosen approach for beginning technical work on the new USSF portal.
Closes #26
> [ADR] Initial technical implementation of USSF portal

- docs/adr/0001-initial-portal-implementation.md
- docs/adr/0002-nextjs.md
This adds an ADR to use NextJS for the new portal client application.
Fixes #24
> [ADR] Use NextJS for the USSF portal client application

- docs/adr/0005-use-Docker-for-running-the-application.md
An ADR on using Docker for local development and a Docker image as a deployment artifact.
Fixes #57 
A WIP. I'd like @suzubara to add anything. Please let me know if I missed something or your thoughts in general.
> [57] ADR |  Use Docker for running the application

- docs/adr/0004-nosql-for-nexjs.md
Adds ADR for using NoSQL database to store non-sensitive user data for the Next.js app.
[Preview here](https://github.com/USSF-ORBIT/ussf-portal/blob/e7e49b9288b7b1715720ae564c8707f3b6ced2ec/docs/adr/0004-nosql-for-nexjs.md). 
Fixes #58 
I added notes on a third option we didn't discuss in engineering sync, but I came across in my research (JSONB in Postgres). I changed this ADR to 'Draft' just in case it brings up any questions that people want to discuss, although I did still mark NoSQL as the chosen outcome.
Let me know if I missed anything, got anything wrong, other feedback, etc. Thanks, team!
> ADR: Use a NoSQL Database for Next.js App

- docs/adr/0006-use-keystone-cms.md
Adds an ADR documenting our CMS decision
Fixes #59
> ADR about CMS decision

- docs/adr/0007-use-mongodb-nodejs-driver.md
This ADR covers the decision to use MongoDB, DocumentDB, and no ODM.
View the pretty version here: https://github.com/USSF-ORBIT/ussf-portal/blob/eecf99d9b35b9074f7208653023154bca95ad56f/docs/adr/0007-use-mongodb-nodejs-driver.md
> docs: Add ADR on database and tooling

- 0008-auth-architecture.md
Adds an ADR that describes our chosen authentication strategy and alternatives we didn't go with. The work described by this ADR is present in https://github.com/USSF-ORBIT/ussf-portal-client/pull/296
Fixes #67
> Authentication ADR

- README.md
- USSF-Portal-Product-Roadmap.md
- acknowledgements.md
- contact-info.md
- design-elements.md
- development-updates.md
- portal-updates.md
- the-team.md
...
*  Included top nav
*  Removed links from home page
* Added more content to Design Elements page
Fixes #
> Microsite updates v2

- README.md
- acknowledgements.md
- contact-info.md
- design-elements.md
- development-updates.md
- portal-updates.md
- the-team.md
...
*  Fixed nav
*  Fixed some bolding issues
* Updated team page
* Removed contact info page
Fixes #
> Microsite updates v3

- USSF-Portal-Product-Roadmap.md
- design-elements.md
- portal-updates.md
...
* Removed feedback link
* Updated Design Elements copy
* 
Fixes #
> Microsite updates v4

- acknowledgements.md
- design-elements.md
...
*  Updated missing links
*  Fixed spacing issue
*  Removed Volunteer Requests section from the Acknowledgements page
Fixes #
> Microsite updates v5

- README.md
- USSF-Portal-Product-Roadmap.md
- acknowledgements.md
- design-elements.md
- development-updates.md
- portal-updates.md
- the-team.md
...
*  Updated roadmap
*  Fixed email address for requesting user research participation
* 
Fixes #
> Microsite updates v6

- docs/adr/0008-auth-architecture.md
- docs/adr/0009-platform-auth-architecture.md
ADR about our chosen strategy for handling authentication & authorization on supporting platforms.
Fixes #99
> docs: ADR about CMS/analytics platform auth

- the-team.md
Updating the microsite with bios for @K-Jurick , @lizlinuxdesign  and Kate! Please review to make sure it says what you want it to say! I was going to include @mdrummerboy09, but I wasn't sure if that was appropriate (please let me know if it is)!
Trussels: bios came from Truss's website
Kat: bio came from Slack
> Adding a few new team members.

- the-team.md
Pulled some past team members into an Alumni section.
> Creating an Alumni section

- docs/README.md
- docs/adr/0011-separate-repo-for-e2e-tests.md
Add an ADR for Separate Repo for E2E tests. See ADR
Fixes SC-561
> docs: add adr 11 Separate Repo for E2E tests

- .github/settings.yml
- e2e/cypress/integration/sites-and-applications.spec.js
> dev: Update e2e test for custom link changes

- .github/workflows/reusable-run-e2e-tests.yml
- .github/workflows/run-e2e-tests.yml
> ci: change docker compose cmd

- e2e/cypress/database/users.js
- e2e/tsconfig.json
* Add missing baseUrl to tsconfig
* Add displayName and theme to e2e user data
> add baseUrl to tsconfig, update user data

- e2e/cypress/e2e/auth.cy.js
Same as [this change](https://github.com/USSF-ORBIT/ussf-portal/pull/158), but for the auth tests. Just updating the test to look for the user's display names.
> test: Update tests to look for new display names

- e2e/docker-compose.yml
This PR updates the e2e configuration to match what is in USSF-ORBIT/ussf-portal-cms#98 likely it can be merged in first since the other PR will fail without it.
Feel free to run the tests if you like.
- yarn services:removeall
- yarn services:up
- yarn e2e:test
- yarn cypress:test
> test: rename variable to match latest name

- docs/how-to/migrations.md
> doc: add migrations documentation

- .github/workflows/reusable-run-e2e-tests.yml
- uses `setup-buildx-action` to install lastest `buildx` and `buildkit` to match our build process in the other repos
> build: add setup-buildx

- .github/workflows/reusable-run-e2e-tests.yml
- add condition to checkout steps for if `github.event_name` is `push` or `pull_request`
- add additional checkout steps that run on `if: ${{ github.event_name == 'merge_group' }}`
> ci: add condition for checking out merge group head ref

- docs/README.md
- docs/how-to/release-testing.md
- docs/how-to/review-pull-request.md
Review the added documentation.
Let me know if I missed anything, have any typos, or if there is some better way to lay this out.
References https://github.com/USSF-ORBIT/ussf-portal-client/pull/999
> docs: add process documents

- docs/README.md
- docs/adr/0019-stricter-lint-checks-and-how-to-add-exceptions.md
Add an ADR describing the why behind USSF-ORBIT/ussf-portal-cms#320
Read the ADR, let me know if you have any feedback.
> docs: add adr for stricter lint checks and adding exceptions

- e2e/playwright/feature/featured-shortcuts.spec.ts
- e2e/playwright/feature/guardian-ideal.spec.ts
- e2e/playwright/portal-client/tests/myspace.spec.ts
- e2e/playwright/portal-client/tests/sites-and-apps.spec.ts
- Update use of the word 'section' to be 'widget' in order to match updates in [this PR](https://github.com/USSF-ORBIT/ussf-portal-client/pull/1015)
> test: Update Add Section labels

- docs/adr/0018-disable-unsafe-regex-in-cms-slug-code.md
Add link to ReDoS tool that helps us diagnose regex issues.
> Add link to ADR 0018

- docs/README.md
- docs/adr/0020-use-aws-certificate-manager-for-dod-tls-certs.md
> docs: add ADR for using AWS Certificate Manager (ACM)

- e2e/package.json
- e2e/playwright/feature/drag-and-drop.spec.ts
- e2e/yarn.lock
Update drag-and-drop e2e test for https://github.com/USSF-ORBIT/ussf-portal-client/pull/1021
> test: Update e2e test for drag-and-drop

- docs/README.md
- docs/adr/0021-disable-no-console-eslint-warning.md
Add an ADR documenting why we disabled no-console eslint warning
> docs: add ADR for disabling no-console

- docs/README.md
- docs/adr/0022-integrating-personnel-data-into-the-portal.md
ADR on the proposed setup for handling personnel data in the portal
> add adr about integrating personnel data into the portal

- docs/how-to/releasing.md
This PR updates the release documentation to reflect the new release process.
These PRs are related in that they update the release-please configs to match what the standard-version configuration process. 
https://github.com/USSF-ORBIT/ussf-portal-cms/pull/358
https://github.com/USSF-ORBIT/ussf-portal-client/pull/1061
> docs: update release documentation to reflect the new process

- e2e/playwright/feature/drag-and-drop-collections.spec.ts
Tests to go with the bug fix here: https://github.com/USSF-ORBIT/ussf-portal-client/pull/1066
> test: Tests for dnd bug fix

- docs/README.md
- docs/adr/0024-graphql-cop.md
ADR on adding GraphQL Cop to our GitHub Actions to test common security issues for GraphQL APIs
> docs: ADR to add GraphQL Cop to GHA

- docs/README.md
- docs/adr/0024-graphql-cop.md
- docs/adr/0025-weather-api.md
Adds ADR for using the National Weather Service API for weather widget.
> chore: Add ADR for NWS API

- docs/how-to/add-a-new-widget.md
Add documentation for adding a new Widget component to My Space in the portal-client repo
> docs: Add documentation for adding a new Widget

- docs/README.md
- docs/adr/0027-enable-playwright-e2e-retries.md
- e2e/playwright.config.ts
As discussed in eng sync this PR enables playwright's [retries](https://playwright.dev/docs/test-retries) feature. See the ADR in this PR for more details.
[build with flakey test](https://github.com/USSF-ORBIT/ussf-portal/actions/runs/6540597046/job/17760904435?pr=322)
```sh
Running 67 tests using 1 worker
✓  1 [cms-chromium] › playwright/cms/tests/01-auth.spec.ts:29:3 › Authentication › redirects a user to the portal log in page if not logged in (658ms)
✓  2 [cms-chromium] › playwright/cms/tests/01-auth.spec.ts:43:3 › Authentication › can log in as a CMS user (2.5s)
✓  3 [cms-chromium] › playwright/cms/tests/01-auth.spec.ts:62:3 › Authentication › can log in as a CMS admin (1.9s)
✓  4 [cms-chromium] › playwright/cms/tests/01-auth.spec.ts:77:3 › Authentication › cannot log in as a user …
```
> feat: enable playwright retries

- .mergify.yml
- e2e/.mergify.yml
- Implements two Merge Queues, one for regular PRs and one for Dependabot/Renovate PRs
- Adds Queue Conditions for # of approvers based on label
- Auto-queue PRs when branch protection rules are met
- Put a time range for when merge actions can occur
> ci(Mergify): configuration update

- docs/README.md
- docs/adr/0028-use-LaunchDarkly-for-feature-flags.md
- Add an ADR retroactively explaining the context for why we chose to use LaunchDarkly Feature Flags
> docs: add launchdarkly adr

- docs/cms_development.md
- e2e/docker-compose.yml
- e2e/playwright/cms/tests/01-auth.spec.ts
- e2e/playwright/feature/portal-auth.spec.ts
- e2e/playwright/models/Login.ts
Add tests for the new redirect feature! See https://github.com/USSF-ORBIT/ussf-portal-client/pull/1144 for details
Some docs from other repos also moving here.
> feat: redirect to support

- docs/README.md
- docs/how-to/Grant-CMS-acess.md
Add how to on adding users to the CMS staging enviorment
> Doc: add Create Grant-CMS-acess.md to howto

- e2e/playwright/feature/portal-auth.spec.ts
Updates test to remove conditional https://github.com/USSF-ORBIT/ussf-portal-client/pull/1152
> fix: redirect for cms login

- docs/README.md
- `TROUBLESHOOTING.MD` had a broken link in `README.MD`
> docs:Update README.md with troubleshooting.md

- e2e/playwright/cms/tests/01-auth.spec.ts
Update tests for https://github.com/USSF-ORBIT/ussf-portal-cms/pull/409
> test: Update tests

- e2e/docker-compose.yml
* Adds new environment variable to docker compose
* Related to PR https://github.com/USSF-ORBIT/ussf-portal-client/pull/1177
> fix: Add new environment variable to client service

- docs/how-to/use-saml-groups.md
Correct the docs to reflect where userId comes from in SLAM.
> docs: Update docs to reflect that we use `Display Name` from SLAM as userId not `UPN`

- docs/how-to/generate-jwt-token.md
Documentation to accompany PR https://github.com/USSF-ORBIT/ussf-portal-client/pull/1191
> chore: Add how-to doc for generating jwt token

- e2e/playwright/feature/drag-and-drop-collections.spec.ts
Minor updates that were the result of changes related to removing the LaunchDarkly flag from around the Drag and Drop code.
> chore: review launchdarkly flags

- e2e/playwright/feature/drag-and-drop-collections.spec.ts
- Update locator in test
Related PR: https://github.com/USSF-ORBIT/ussf-portal-client/pull/1222
> test: Update drag-and-drop test

- e2e/playwright/cms/tests/navigation.spec.ts
- e2e/playwright/feature/bookmark-hover-description.spec.ts
- e2e/playwright/feature/document.spec.ts
- e2e/playwright/feature/drag-and-drop-collections.spec.ts
- e2e/playwright/portal-client/tests/sites-and-apps.spec.ts
Tests for PR: https://github.com/USSF-ORBIT/ussf-portal-client/pull/1220
> test: Update tests to address a11y updates

- docs/development.md
- docs/development/additional-testing-tools.md
- docs/development/code-coverage-testing.md
- docs/development/feature-flags.md
- docs/development/local-dev-with-docker.md
- docs/development/postgres-migrations.md
- docs/development/pr-commit-format.md
This PR concludes planned updates to the organization of development documentation. Additionally, I replaced the original table of contents using a tool that generates a nested list based on header levels, which I find easier to navigate when looking for specific details. I've applied the same generated table to all sub-pages with multiple headers for ease of navigation.
> docs: :art: Final reorganization of development documentation

- e2e/playwright/feature/article-tag-label-results.spec.ts
- e2e/playwright/feature/landing-page.spec.ts
- e2e/playwright/feature/saml.spec.ts
- e2e/playwright/feature/search-filter.spec.ts
- e2e/playwright/models/KeystoneAnnouncement.ts
- e2e/playwright/models/KeystoneArticle.ts
Update the CSS selectors in the E2E tests to reflect the node upgrade in the CMS
> chore: Update E2E css selectors to reflect the node upgrade in the CMS
